import type { Metadata } from 'next';
import { Inter, Open_Sans, JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { CSPostHogProvider, ReduxProvider } from './providers';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });
const openSans = Open_Sans({ subsets: ['latin'] });
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CSPostHogProvider>
        <ReduxProvider>
          <body className={cn(openSans.className, jetbrainsMono.variable)}>
            {children}
          </body>
        </ReduxProvider>
      </CSPostHogProvider>
    </html>
  );
}
